server:
  port: 25100
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25101/knox_dev_db
    username: knox_dev_user
    password: knox_dev_pass
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        types:
          print:
            banner: false
  main:
    banner-mode: off
  freemarker:
    enabled: false
  groovy:
    template:
      enabled: false
  h2:
    console:
      enabled: false
  mustache:
    enabled: false
  thymeleaf:
    enabled: false

jwt:
  issuer: knoxdev
  key:
    id: abd1cf61f949ddeb8d32
    pkcs8: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCd7MbjKn1undHqB55o9cdobuWjfoIfCX6YktSWIv6URtvfl9FpCvokJSsTVG+aWeqzMbfLFLPj52Y8356U9F0aUNclY5JMWNEfkInSWW9aXLQ/SFMW5M0skd77poNjXUAzHZXwVFR1fvNDGc1ZmzLDf86tQaxbA1ZaD160lgWmpaE8N0DQ6j+1YPpDsKIIfhzzys/2+/az3tJfLphxHSD5x6p96XqAVwKf/jYEyD0rCDjYX9DCW5GHVu9SB2Jj8yZxXCuKYJEo5oVHgfEda3InGnP5VzF6TzZz8vtbwTMo8nfurKMmzTNS+GxMRjMUw/Z/2ZKsk/KCW534mFcryCn7AgMBAAECggEBAJhaihEzt6iUlqN5UCigHA0zF1VgQbYhmcElvfNNtV5k8c/Gjh8RmPpv5RuT1MsKvfK8HzzLLzTJ04cckMfQ61Ts8nI+mjAPa0hRT7Tf1R5O2xFF++rVNt8tpvoNzSl6F+p4O2OMZ6Kmo5ZzePleUV3rmf7poZZ4JMFjnJEJPlBia5snzswaIDg+HNEnIl44+VnIRgIHZmbsRhFlXL3bVDbXMlAdaySYh4zVCMxzAM51Tiah8V/IUpyGddyraRC3L0DtLlZi7RcM8U1xy2ZX5Va8F46Y97L51V+QlBxLTq3A9IoDh8zHezX0svbdUg22eay3ngPQDWuKagkUnfvUvMkCgYEAzXECtNWrMgqTehFyIsMHZCK34g3nknXNumS95ue7PQc1F5qCaE5rd0nI2sLS7ZqRcsG9sxr1uP9jdVSZAprLcK+Rj/FGTR/5xicx+yNQfHsyfjEQiuVPYT40kXsRJDDa7QorYSwn9i61nozBUqNN5GbHbY6AFzIvM5MXJPxgaUcCgYEAxMou6B0LO4qODma2MD61ZgwhbgVFevPAje6UL88Q4IqoE9tVgFQemhss2+ru53lX8i/JFGMD1VhXn6ppqoz1CE3coxcsE1VNMW3GIvHorAZx2ktyPtRzFkzw3rBO5u6aPnzNBA9fDpikgt36j+lxqvba+l/J/UD5XwZalY8JU60CgYEAwuI2eAbM7J59wek0xWcO5t3MY8Ne7l+T9gJE5vricoUYxzhKBtqFNVaoE2WHI+Bho2PIKVQkzwZtecrzjzX6UP4rbkmpr9XqYh+iWSLp4fwYLP8sOyZGQ+/3fB4rZ5J0yzG/buGtUuqCXVIWveauKEGbYwEv31E614jsBqjmaFcCgYEAloMBH1zfc3nErvUWEY5U1akfhHOZsbFvK983Dd30zZifdxiBq7Yq9bklNUrZ0Mb5Ye30gJg+nVWFJ0SCrwRCgUh0IXUeq+bJNK3+JkoZqEEBoXGk/rMlFwBgFiKJJo2GAZcYgytyi8ppwQIgmyN0YcuOroLHDeE9GdXVQKB3BL0CgYBvUIy3RDkfR5lIr6Jr1QajVfoyD9C0b2IlOhm9P5X1Zq/vExDJ/fo65WLOqK1NnbHFg1O92TJQbjBTQvW0jzJTr527a33WZGOf4zrptHIGBYWuz30J1wlDFiVXDkzR598DPhlILcL2cfGGdfFZsiagqNgy42tIT5NaIYLCoOMRmw==
    x509: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnezG4yp9bp3R6geeaPXHaG7lo36CHwl+mJLUliL+lEbb35fRaQr6JCUrE1RvmlnqszG3yxSz4+dmPN+elPRdGlDXJWOSTFjRH5CJ0llvWly0P0hTFuTNLJHe+6aDY11AMx2V8FRUdX7zQxnNWZsyw3/OrUGsWwNWWg9etJYFpqWhPDdA0Oo/tWD6Q7CiCH4c88rP9vv2s97SXy6YcR0g+ceqfel6gFcCn/42BMg9Kwg42F/QwluRh1bvUgdiY/MmcVwrimCRKOaFR4HxHWtyJxpz+Vcxek82c/L7W8EzKPJ37qyjJs0zUvhsTEYzFMP2f9mSrJPyglud+JhXK8gp+wIDAQAB
